theme: jekyll-theme-dinky
title: Kshitij Kumar Singh Chauhan
description: Hi, this is Kshitij. I am currently pursuing my bachelors in computer science and engineering from International Institute Of Information And Technology, Naya Raipur.
I believe in the classical principle of simple is beautiful , and try to implement the same in my solutions to the questions that our society encounters at the technical front. 
